### ISSUE TITLE
Fails to build on aclocal version check

### ISSUE THREAD

**Issue by prokoudine** [yan-zlobin/mbreader#1]
/home/alex/soft/desktop/mbreader/missing: line 81: aclocal-1.13: команда не найдена
WARNING: 'aclocal-1.13' is missing on your system.

Is this limitation really necessary, or can you instead add autogen.sh with if/elif conditions to allow for more aclocal/automake versions to be allowed? :)

**Comment by yan-zlobin** [comment]
It is not necessary and be changed to smaller makefile.

**Comment by yan-zlobin** [comment]
This will help: ln -s aclocal{some-exists-version} aclocal-1.13
